spring.application.name=demo
server.port=9090
gemini.api.key=AIzaSyAEedoTUPXiMb-k9O8upRlv0eY3VPhY0X8

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/PolicyHub-Realm

spring.security.oauth2.client.registration.PolicyHub-Backend.client-id=PolicyHub-Backend
spring.security.oauth2.client.registration.PolicyHub-Backend.client-secret=n6xUyPX0450oZ1SDiWmr55g19svRVI5w
spring.security.oauth2.client.registration.PolicyHub-Backend.scope=openid,profile,roles,email
spring.security.oauth2.client.registration.PolicyHub-Backend.provider=keycloak-provider

spring.security.oauth2.client.provider.keycloak-provider.issuer-uri=http://localhost:8080/realms/PolicyHub-Realm

# The redirect URI for the standard Spring Security flow
spring.security.oauth2.client.registration.PolicyHub-Backend.redirect-uri=https://localhost:5173/*
spring.data.mongodb.uri=mongodb://localhost:27017/PolicyHub